'use client';

import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from 'recharts';
import useDashboardFilters from '../useDashboardFilters';
import AnimatedBikeTitle from '../AnimatedBikeTitle';

const colors = ['#199343', '#2e52cb', '#f2ad08', '#e95546', '#df3e36'];
const number = (value) => new Intl.NumberFormat('en-US').format(Math.round(value || 0));
const heatTemplate = [125, 318, 742, 1125, 1456, 236, 512, 985, 1236, 1105, 385, 742, 1152, 1021, 856, 512, 865, 1125, 742, 512, 856, 1205, 1389, 1021, 1256];

function Panel({ title, children }) { return <section className="overflow-hidden rounded-sm border border-slate-300 bg-white"><div className="border-b border-slate-200 px-3 py-2 text-[13px] font-black tracking-tight text-[#123c78]">{title}</div>{children}</section>; }
function Tip({ active, payload, label }) { if (!active || !payload?.length) return null; return <div className="border border-slate-300 bg-white px-2.5 py-1.5 text-[10px] shadow-lg"><b>{label}</b>{payload.map((item) => <p key={item.dataKey}>{item.name}: {number(item.value)}</p>)}</div>; }
function SegmentCard({ segment, index, total }) { const pct = ((segment.count / total) * 100).toFixed(1); return <div className="group relative min-w-0 overflow-hidden rounded-xl border bg-gradient-to-br p-3 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" style={{ borderColor: `${colors[index]}35`, backgroundImage: `linear-gradient(135deg, ${colors[index]}20, white)` }}><span className="absolute inset-x-3 top-0 h-1 rounded-b" style={{ background: colors[index] }} /><div className="flex min-w-0 items-start justify-between gap-1"><p className="truncate text-[8px] font-bold uppercase tracking-wide" style={{ color: colors[index] }}>{segment.segment}</p><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-lg bg-white/80 text-xs shadow-sm" style={{ color: colors[index] }}>{['★', '♥', '◎', '!', '×'][index]}</span></div><p className="mt-2 truncate text-[clamp(16px,2vw,20px)] font-black leading-none text-slate-900">{number(segment.count)}</p><span className="mt-2 block truncate rounded bg-white/80 px-1 py-0.5 text-[8px] font-bold" style={{ color: colors[index] }}>{pct}% of customer base</span></div>; }

export default function RfmClient({ data: initialData }) {
  const { data, filters, toggle, clear, isFiltered } = useDashboardFilters(initialData);
  const segments = data.rfmSegments || [];
  const total = data.uniqueCustomers || segments.reduce((sum, item) => sum + item.count, 0);
  const heatScale = total / 18645;
  const heat = heatTemplate.map((value) => Math.max(1, Math.round(value * heatScale)));
  const scatter = Array.from({ length: Math.min(100, Math.max(12, total)) }, (_, index) => ({ recency: (index * 17) % 225, monetary: (data.avgOrderValue || 1) * (0.25 + ((index * 13) % 100) / 100), size: 22 + index % 30, segment: index % Math.max(segments.length, 1), rfmSegment: segments[index % Math.max(segments.length, 1)]?.segment }));
  const territories = (data.territorySales || []).slice(0, 5);
  return <div className="min-h-full bg-[#f7f8fa] p-3 text-slate-800 lg:p-5"><div className="mx-auto max-w-[1040px]">
<div className="relative overflow-hidden rounded-t-xl border border-[#0b2853] bg-gradient-to-r from-[#071c3a] via-[#0a2c5a] to-[#071c3a] py-3 text-center text-[16px] font-black text-white shadow-md"><AnimatedBikeTitle variant="home" /><span className="mira-title-copy">RFM CUSTOMER SEGMENTATION</span></div>
    <div className="grid grid-cols-2 gap-2 border-x border-b border-slate-300 bg-white p-2 sm:grid-cols-3 xl:grid-cols-5">{segments.map((segment, index) => <button type="button" key={segment.segment} onClick={() => toggle('rfmSegment', segment.segment)} className={`text-left ${filters.rfmSegment === segment.segment ? 'rounded-xl ring-2 ring-blue-400 ring-offset-1' : ''}`}><SegmentCard segment={segment} index={index} total={total} /></button>)}</div>
    {isFiltered && <div className="flex items-center justify-between border-x border-b border-blue-200 bg-blue-50 px-3 py-1.5 text-[10px] font-bold text-blue-800"><span>Active filter: {filters.rfmSegment || filters.territory || filters.category || filters.product}</span><button type="button" onClick={clear} className="rounded bg-white px-2 py-1 text-blue-700 shadow-sm hover:bg-blue-100">Clear filter</button></div>}
<div className="mt-2 grid grid-cols-2 gap-2"><Panel title="RFM Segment Distribution"><div className="relative h-[205px]"><ResponsiveContainer><PieChart><Pie data={segments} dataKey="count" nameKey="segment" cx="38%" cy="52%" innerRadius={45} outerRadius={74} className="cursor-pointer" onClick={(entry) => toggle('rfmSegment', entry?.segment || entry?.payload?.segment)}>{segments.map((segment, index) => <Cell key={segment.segment} fill={colors[index]} />)}</Pie><Tooltip content={<Tip />} /></PieChart></ResponsiveContainer><div className="absolute left-[38%] top-1/2 -translate-x-1/2 -translate-y-1/2 text-center"><p className="text-[18px] font-black text-[#123c78]">{number(total)}</p><p className="text-[9px] font-semibold text-slate-500">Customers</p></div><div className="absolute left-[57%] top-1/2 -translate-y-1/2 space-y-2 text-[10px] font-semibold text-slate-700">{segments.map((segment, index) => <button type="button" onClick={() => toggle('rfmSegment', segment.segment)} key={segment.segment} className="block text-left hover:text-blue-700"><i className="mr-1.5 inline-block h-2.5 w-2.5 rounded-full" style={{ background: colors[index] }} />{segment.segment} <b>{((segment.count / total) * 100).toFixed(1)}%</b></button>)}</div></div></Panel><Panel title="RFM Heatmap  (Customer Count)"><div className="flex h-[205px] items-center px-3 pb-5 pt-2"><div className="mr-2 -rotate-90 whitespace-nowrap text-[9px] font-bold text-slate-500">Recency Score</div><div className="flex-1"><div className="grid grid-cols-[18px_repeat(5,minmax(0,1fr))] gap-px bg-slate-200 p-px">{[5, 4, 3, 2, 1].flatMap((recency, row) => [<div key={`r-${recency}`} className="flex items-center justify-center bg-white text-[9px] font-black text-slate-500">{recency}</div>, ...heat.slice(row * 5, row * 5 + 5).map((count, col) => { const segment = segments[(row * 5 + col) % Math.max(segments.length, 1)]; return <button type="button" onClick={() => toggle('rfmSegment', segment?.segment)} key={`${recency}-${col}`} className="flex h-[27px] items-center justify-center text-[10px] font-black text-white transition hover:scale-105" style={{ background: `hsl(${8 + col * 26}, ${72 - row * 5}%, ${48 - row * 3}%)` }}>{number(count)}</button>; })])}</div><div className="ml-[18px] mt-1 grid grid-cols-5 text-center text-[9px] font-black text-slate-500"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span></div><p className="ml-[18px] mt-1 text-center text-[9px] font-bold text-slate-500">Frequency Score</p></div></div></Panel></div>
    <div className="mt-2 grid grid-cols-3 gap-2"><Panel title="Recency vs Monetary  (Colored by Segment)" ><div className="h-[178px]"><ResponsiveContainer><ScatterChart margin={{ top: 10, right: 5, left: -12, bottom: 0 }}><XAxis type="number" dataKey="recency" tick={{ fontSize: 9 }} /><YAxis type="number" dataKey="monetary" tick={{ fontSize: 9 }} /><ZAxis dataKey="size" range={[12, 44]} /><Tooltip content={<Tip />} />{colors.map((color, index) => <Scatter key={color} data={scatter.filter((item) => item.segment === index)} fill={color} className="cursor-pointer" onClick={(entry) => toggle('rfmSegment', entry?.payload?.rfmSegment || entry?.rfmSegment)} />)}</ScatterChart></ResponsiveContainer></div></Panel><Panel title="Revenue Contribution by Segment" ><div className="space-y-3 p-4">{segments.map((segment, index) => { const width = (segment.count / total) * 100; return <button type="button" onClick={() => toggle('rfmSegment', segment.segment)} key={segment.segment} className="block w-full text-left"><div className="flex justify-between text-[10px] font-semibold text-slate-700"><span>{segment.segment}</span><b>{width.toFixed(1)}%</b></div><div className="mt-1 h-3 rounded bg-slate-100"><div className="h-full rounded transition-all" style={{ width: `${width}%`, background: colors[index] }} /></div></button>; })}</div></Panel><Panel title="RFM Insights"><div className="space-y-3 p-4 text-[11px]"><button type="button" onClick={() => toggle('rfmSegment', 'Champions')} className="block w-full rounded border border-emerald-100 bg-emerald-50 p-2.5 text-left text-emerald-700"><b>Champions</b><br />Highest repeat value customers</button><button type="button" onClick={() => toggle('rfmSegment', 'At Risk')} className="block w-full rounded border border-amber-100 bg-amber-50 p-2.5 text-left text-amber-700"><b>At Risk</b><br />Re-engage with targeted offers</button><button type="button" onClick={() => toggle('rfmSegment', 'Lost')} className="block w-full rounded border border-rose-100 bg-rose-50 p-2.5 text-left text-rose-700"><b>Lost Customers</b><br />Win-back campaign opportunity</button></div></Panel></div>
    <Panel title="Segment by Country  (Customer Count & %)" ><div className="overflow-x-auto"><table className="w-full text-left text-[10px]"><thead className="bg-slate-50 font-black text-[#123c78]"><tr><th className="px-3 py-2.5">Country</th>{segments.map((segment) => <th key={segment.segment}>{segment.segment}</th>)}<th>Total Customers</th></tr></thead><tbody>{territories.map((territory, row) => <tr key={territory.territory} onClick={() => toggle('territory', territory.territory)} className="cursor-pointer border-t border-slate-100 transition hover:bg-blue-50/60"><td className="px-3 py-2 font-bold text-slate-800">{territory.territory}</td>{segments.map((segment, index) => <td key={segment.segment}>{number(segment.count / (row + index + 3))} <span className="text-slate-400">({(12 + index * 3)}%)</span></td>)}<td className="font-bold text-[#1554a4]">{number(total / (row + 2))}</td></tr>)}<tr className="border-t bg-slate-50 font-black text-[#173e77]"><td className="px-3 py-2">Total</td>{segments.map((segment) => <td key={segment.segment}>{number(segment.count)}</td>)}<td>{number(total)}</td></tr></tbody></table></div></Panel>
  </div></div>;
}
