/// Campaign data for the native interactive AdventureWorks report.
table Campaign
	lineageTag: 9f23aa11-5e2a-4dad-818f-2c727f04aad8

	/// Business measure used by the AdventureWorks report.
	measure 'Campaign Count' = DISTINCTCOUNT('Campaign'[Campaign])
		formatString: #,##0
		lineageTag: 0aca1ab5-6e73-41ef-b928-e6aa8841a478

	/// Business measure used by the AdventureWorks report.
	measure 'Total Audience' = SUM('Campaign'[Audience])
		formatString: #,##0
		lineageTag: 9596dc0b-9a87-4b11-b266-704fd70ddf54

	/// Business measure used by the AdventureWorks report.
	measure 'Active Campaigns' = CALCULATE([Campaign Count], KEEPFILTERS('Campaign'[Status] = "Ready"))
		formatString: #,##0
		lineageTag: 596871e5-cc62-4441-ad95-60b59509ae0b

	/// Campaign Key imported from the prepared AdventureWorks dataset.
	column 'Campaign Key'
		dataType: int64
		isHidden
		lineageTag: 90006e8d-07c6-4a87-9139-1f6eebffed50
		summarizeBy: none
		sourceColumn: CampaignKey

	/// Segment imported from the prepared AdventureWorks dataset.
	column Segment
		dataType: string
		lineageTag: e85371df-fe00-4f98-8bd7-093976b4f993
		summarizeBy: none
		sourceColumn: RFMSegment

	/// Campaign imported from the prepared AdventureWorks dataset.
	column Campaign
		dataType: string
		lineageTag: d9609145-9505-434e-a044-e05425cd63f3
		summarizeBy: none
		sourceColumn: Campaign

	/// Campaign Type imported from the prepared AdventureWorks dataset.
	column 'Campaign Type'
		dataType: string
		lineageTag: 06856a31-500f-406a-b676-3196784355dd
		summarizeBy: none
		sourceColumn: CampaignType

	/// Audience imported from the prepared AdventureWorks dataset.
	column Audience
		dataType: int64
		lineageTag: b73b8a2c-0f13-4020-a0f8-5e8872e4c846
		summarizeBy: none
		sourceColumn: Audience

	/// Offer imported from the prepared AdventureWorks dataset.
	column Offer
		dataType: string
		lineageTag: fbaf7ccd-bc87-4731-b5f1-950d1e5ca066
		summarizeBy: none
		sourceColumn: Offer

	/// Channel imported from the prepared AdventureWorks dataset.
	column Channel
		dataType: string
		lineageTag: e6a4d180-8a5b-417f-9bdc-012fb60a30f9
		summarizeBy: none
		sourceColumn: Channel

	/// Status imported from the prepared AdventureWorks dataset.
	column Status
		dataType: string
		lineageTag: 6ecd99a6-5279-407d-8fef-8f9e0852722f
		summarizeBy: none
		sourceColumn: Status

	partition Campaign = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\\Users\\ofaru\\OneDrive\\Masaüstü\\Dashboard\\PowerBI\\Data\\Campaigns.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"CampaignKey", Int64.Type}, {"RFMSegment", type text}, {"Campaign", type text}, {"CampaignType", type text}, {"Audience", Int64.Type}, {"Offer", type text}, {"Channel", type text}, {"Status", type text}}, "en-US")
				in
					#"Changed Types"

