/// Territory data for the native interactive AdventureWorks report.
table Territory
	lineageTag: 506c1b55-cca5-4ebf-a510-5283c0a3b10f

	/// Territory Key imported from the prepared AdventureWorks dataset.
	column 'Territory Key'
		dataType: string
		isHidden
		lineageTag: f1c2ba94-8918-484c-8cc6-96159a41c303
		summarizeBy: none
		sourceColumn: TerritoryKey

	/// Region imported from the prepared AdventureWorks dataset.
	column Region
		dataType: string
		lineageTag: 56aec701-c2e6-4773-b7d2-d33602829b63
		summarizeBy: none
		sourceColumn: Region

	/// Country imported from the prepared AdventureWorks dataset.
	column Country
		dataType: string
		lineageTag: 76a45414-fcac-4105-b7f5-74e5a010e41e
		summarizeBy: none
		sourceColumn: Country

	/// Group imported from the prepared AdventureWorks dataset.
	column Group
		dataType: string
		lineageTag: 3eca93c3-379f-4d1e-877b-34a356fe87d5
		summarizeBy: none
		sourceColumn: TerritoryGroup

	partition Territory = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents("C:\\Users\\ofaru\\OneDrive\\Masaüstü\\Dashboard\\PowerBI\\Data\\DimTerritory.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Types" = Table.TransformColumnTypes(#"Promoted Headers", {{"TerritoryKey", type text}, {"Region", type text}, {"Country", type text}, {"TerritoryGroup", type text}}, "en-US")
				in
					#"Changed Types"

